INSERT INTO DRINKER_TYPE( NAME , VOLUME ) VALUES ('Man', 5);
INSERT INTO DRINKER_TYPE( NAME , VOLUME ) VALUES ('Cat', 1);
INSERT INTO CONTAINER_TYPE( NAME , VOLUME ) VALUES ('Bottle', 1.5);
INSERT INTO CONTAINER_TYPE( NAME , VOLUME ) VALUES ('Bowl', 0.3);